### ISSUE TITLE
how to set the font

### ISSUE THREAD

**Issue by BenxiaHu** [zwbetz-gh/cayman-hugo-theme#3]
Hello,
   the theme (https://themes.gohugo.io/theme/cayman-hugo-theme/) looks great! Would you like to tell me how to change the font color of the menus, and remove the rectanges highlighed in red?

![image](https://user-images.githubusercontent.com/12387462/104138698-d97b1a00-5373-11eb-8734-8443026f5ba2.png)

Best,

**Comment by zwbetz-gh** [comment]
You can do this by overriding the theme's stylesheet. Sample steps:

1. Make sure the **extended** version of Hugo is installed
2. Copy file `themes/cayman-hugo-theme/assets/scss/cayman.scss` to a new file at `assets/scss/cayman.scss`. Per Hugo's lookup order, this new file will be used when building the site
3. Add the following SCSS to the bottom of the file. Change the color to whatever you like

```scss
// Overrides
.btn {
  color: rgba(255, 255, 255, 0.7);
  background-color: initial;
  border: initial;
}
```
