### ISSUE TITLE
Editing the _config.yml for github pages

### ISSUE THREAD

**Issue by royben** [zwbetz-gh/cayman-hugo-theme#4]
Hi there,

I'm using the Cayman theme for my github page.
Trying to edit the _config.yml file colors, but it doesn't seem to take effect.

Am I missing something ?

Here is my config file, Thanks!

---------------------------------------------------------------------------

```
theme: jekyll-theme-cayman

params:
  # Header text, can be markdown
  project_name: Resonance
  project_tagline: Realtime C# Communication Framework
  
  # Breakpoints
  large_breakpoint: 64em
  medium_breakpoint: 42em

  # Header colors
  header_heading_color: "#fff"
  header_background_color: "#ff0000"
  header_background_color_secondary: "#155799"

  # Text colors
  section_headings_color: "#FF0000"
  body_text_color: "#606c71"
  body_link_color: "#1e6bb8"
  blockquote_text_color: "#819198"

  # Code colors
  code_background_color: "#f3f6fa"
  code_text_color: "#567482"

  # Border colors
  border_color: "#dce6f0"
  table_border_color: "#e9ebec"
  hr_border_color: "#eff0f1"
```
